---
title: "Lung cancer survival analysis"
author: "Bortolussi Lorenzo, Cartago Marco, Tonet Lorenzo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(ggplot2)
library(corrplot)
library(dplyr)
library(tidyr)
library(ggExtra)
library(patchwork)
```

# NCCTG Lung Cancer Data
## Dataset description
description

```{r importing dataset}
data = survival::cancer
```

```{r summary}
summary(data)
```

```{r factors to factors, echo = FALSE}
data$sex <- factor(data$sex)
data$status <- factor(data$status)
data$ph.ecog <- factor(data$ph.ecog)
data$ph.karno <- factor(data$ph.karno)
data$pat.karno <- factor(data$pat.karno)
```

```{r additional variables}
data$age.cat <- cut(
    data.nm$age, 
    breaks=c(0, 50, 70, Inf), 
    labels=c("<50", "50-70", "70+")
)
```

## NAs
```{r na overview}
colSums(is.na(data))
```

```{r NA distribution}
nas <- data.frame(var=colnames(data), na=colSums(is.na(data)))
ggplot(nas, aes(x=var, y=na))+ 
  geom_bar(stat="identity")+
  xlab("Variables") +
  ylab("Number of NAs") +
  theme_grey()

```

```{r NAs (conditioned to sex)}

dataM <-data.frame(
  var=colnames(data[data$sex=="1",]), 
  sex="Male", 
  na=colSums(is.na(data[data$sex=="1",]))
)

dataF <- data.frame(
  var=colnames(data[data$sex=="2",]),
  sex="Female",
  na=colSums(is.na(data[data$sex=="2",]))
)

nas_conditioned <- rbind(dataM, dataF)
nas_conditioned_df <- data.frame(var=colnames(data), na=colSums(is.na(data)))

ggplot(nas_conditioned, aes(x=var, y=na))+ 
  xlab("Variables") +
  ylab("Number of NAs") +
  geom_bar(stat="identity")+
  facet_wrap(~sex) +
  coord_flip()
```
```{r NAs (conditioned to status)}
data1 <-data.frame(
  var=colnames(data[data$status=="1",]),
  status="1",
  na=colSums(is.na(data[data$status=="1",]))
)

data2 <- data.frame(
  var=colnames(data[data$status=="2",]),
  status="2",
  na=colSums(is.na(data[data$status=="2",]))
)


nass <- rbind(data1, data2)
nas <- data.frame(var=colnames(data), na=colSums(is.na(data)))

ggplot(nass, aes(x=var, y=na))+
  xlab("Variables") +
  ylab("Number of NAs") +
  geom_bar(stat="identity")+
  facet_wrap(~status) +
  coord_flip() +
  theme_bw()
```


```{r NAs prediction}
hasna <- as.numeric(rowSums(is.na(data)) > 0)
na.corr.data <- cbind(data, hasna)
na.corr.data <- na.corr.data[-9]

m <- glm(
  hasna ~ inst + ph.ecog + ph.karno + pat.karno + sex + time,
  family = binomial(link="logit"),
  data=na.corr.data
)
```

## Exploratory data analysis
### Univariate analysis
```{r Age variable}

p1 = ggplot(data = data, aes(x = age, y = ..density..)) +
  geom_histogram(bins = 20) +
  geom_density(alpha = 0.5, colour="darkgray") +
  labs(title = "Age Distribution", x = "Age", y = "Count") +
  theme_minimal()

p2 = ggplot(data = data, aes(x = age)) +
  geom_boxplot() +
  labs(title = "Age Boxplot", x = "Age", y = "Count") +
  theme_minimal()

p1 + p2 + plot_layout(heights = c(5,1))
```

### Bivariate analysis